{
 "title": "Credit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(level) AS \"level\",\n  level AS \"level\"\nFROM log.creditlog\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, level\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(level) AS \"Information\"\nFROM log.creditlog\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  level = 'Information'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(level) AS \"Warning\"\nFROM log.creditlog\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  level = 'Warning'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(level) AS \"Error\"\nFROM log.creditlog\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  level = 'Error'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Logs API",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp as \"time\",\r\n  ((properties->> 'Url')::text) as \"url\",\r\n  ((properties->> 'RequestBody')::text) as \"requestBody\",\r\n  ((properties->> 'ResponseBody')::text) as \"response\",\r\n  ((properties->> 'ResponseCode')::text) as \"code\"\r\nFROM log.creditlog\r\nWHERE ((properties->> 'Url')::text) != ''\r\nORDER BY time desc"
    }
   ]
  }
 ]
}